---
- name: Update Apt Cache
  become: true
  apt:
    update_cache: yes

- name: Install Required Packages
  become: true
  apt:
    name:
      - ca-certificates
      - curl
    state: present

- name: Create Keyrings Directory
  become: true
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Docker GPG key
  become: true
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'
