- name: Create Containerd Configuration Directory
  become: true
  ansible.builtin.file:
    path: /etc/containerd
    state: directory
    mode: '0755'

- name: Remove Existing Containerd Configuration
  become: true
  file:
    path: /etc/containerd/config.toml
    state: absent

- name: Generate Default Containerd Configuration
  become: true
  ansible.builtin.command:
    cmd: containerd config default
  register: containerd_default_config
  changed_when: false

- name: Write Containerd Configuration to /etc/containerd/config.toml
  become: true
  ansible.builtin.copy:
    content: "{{ containerd_default_config.stdout }}\n"
    dest: /etc/containerd/config.toml
    owner: root
    group: root
    mode: '0644'

- name: Update Containerd Configuration - Enable Systemd Cgroup
  become: true
  ansible.builtin.replace:
    path: /etc/containerd/config.toml
    regexp: 'SystemdCgroup = false'
    replace: 'SystemdCgroup = true'
  notify: Restart Containerd

- name: Update Containerd Configuration - Update Sandbox Image
  become: true
  ansible.builtin.replace:
    path: /etc/containerd/config.toml
    regexp: 'sandbox_image = "registry\.k8s\.io/pause:\d+\.\d+"'
    replace: 'sandbox_image = "registry.k8s.io/pause:{{ sandbox_pause_image_version }}"'
  notify: Restart Containerd

- meta: flush_handlers

- name: Verify Containerd Service Status
  become: true
  ansible.builtin.command:
    cmd: systemctl status containerd
  register: containerd_status
  changed_when: false
  failed_when:
    - "'containerd successfully booted' not in containerd_status.stdout"
    - "'level=warning' in containerd_status.stdout or 'level=error' in containerd_status.stdout"
