---
- name: Remove Docker and ContainerD Directories
  become: true
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /var/lib/docker
    - /var/lib/containerd

- name: Remove Docker APT Sources and Keyring
  become: true
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/apt/sources.list.d/docker.list
    - /etc/apt/keyrings/docker.asc
