apiVersion: v1
kind: Service
metadata:
  name: kube-apiserver-lb
  namespace: kube-system
spec:
  selector:
    component: kube-apiserver
  type: LoadBalancer
  loadBalancerIP: 192.168.2.50
  ports:
    - name: https
      port: 6443
      targetPort: 6443
      protocol: TCP
