apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb-resources
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/pleejr/homelab
    targetRevision: HEAD
    path: argo/argocd/projects/homelab/metallb/resources
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
