apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  project: default
  sources:
    - chart: longhorn
      repoURL: https://github.com/pleejr/longhorn
      targetRevision: 1.8.1
      path: chart
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
