apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  project: default
  source:
      repoURL: https://github.com/pleejr/longhorn
      targetRevision: v1.8.1
      path: chart
      helm:
        valueFiles:
        - values/homelab.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
