---
- name: Collect MAC Addresses
  hosts: allnodes
  gather_facts: true
  tasks:

  - name: Get Default MAC Address
    set_fact:
      mac_address: "{{ ansible_default_ipv4.macaddress }}"

- name: Verify Unique MAC Addresses
  hosts: localhost
  gather_facts: false
  tasks:

  - name: Gather & Check MAC Addresses
    set_fact:
      mac_addresses: "{{ hostvars | selectattr('mac_address', 'defined') | map(attribute='mac_address') | list }}"
    failed_when: mac_addresses | unique | length != mac_addresses | length
