---
- name: Check All Nodes for Prerequistes
  hosts: all_groups
  become: true
  gather_facts: false
  roles:
  - check_all_nodes

- name: Prepare All Nodes
  hosts: all_nodes
  become: true
  gather_facts: false
  roles:
  - prep_all_nodes

- name: Initialize Kubernetes Cluster
  hosts: primary_node
  become: true
  gather_facts: false
  roles:
  - init_cluster

- name: Install CNI - Calico
  hosts: all_nodes
  become: false
  gather_facts: false
  roles:
  - install_cni_calico

# more work needs to be done to ensure a smooth automated join
# for now, run the following on the control plane node:
#   1)  kubeadm token create --print-join-command
#       use this join command and append "--control-plane --certificate-key <cert_key>"
#   2)  sudo kubeadm init phase upload-certs --upload-certs
#       use the certificate key from this command with the previous join command to join a control node
#   3)  join worker nodes with the unaltered join command

# - name: Join Nodes to Cluster
#   hosts: all_nodes
#   become: true
#   gather_facts: false
#   roles:
#   - join_nodes

# - name: Check Cluster Readiness
#   hosts: primary_node
#   become: false
#   gather_facts: false
#   roles:
#   - check_cluster
