apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb-configs
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:pleejr/homelab.git
    targetRevision: HEAD
    path: argo/argocd/projects/homelab/metallb/metallb-configs.yml
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  dependsOn:
    - metallb-chart
  