all:
  hosts:
    node01:
      ansible_host: node01
      ansible_user: pleejr
      node_ip_allocation: 192.168.2.30
    node02:
      ansible_host: node02
      ansible_user: pleejr
      node_ip_allocation: 192.168.2.31
    node03:
      ansible_host: node03
      ansible_user: pleejr
      node_ip_allocation: 192.168.2.32
    node04:
      ansible_host: node04
      ansible_user: pleejr
      node_ip_allocation: 192.168.2.33
    node05:
      ansible_host: node05
      ansible_user: pleejr
      node_ip_allocation: 192.168.2.34
    node06:
      ansible_host: node05
      ansible_user: pleejr
      node_ip_allocation: 192.168.2.35
    node07:
      ansible_host: node05
      ansible_user: pleejr
      node_ip_allocation: 192.168.2.36
    node08:
      ansible_host: node05
      ansible_user: pleejr
      node_ip_allocation: 192.168.2.37
    node09:
      ansible_host: node05
      ansible_user: pleejr
      node_ip_allocation: 192.168.2.38
    node10:
      ansible_host: node05
      ansible_user: pleejr
      node_ip_allocation: 192.168.2.39
  children:
    all_groups:
      children:
        local:
          hosts:
            localhost:
              ansible_connection: local
        all_nodes:
          hosts:
            node01: {}
            node02: {}
            node03: {}
            node04: {}
            node05: {}
            node06: {}
            node07: {}
            node08: {}
            node09: {}
            node10: {}
        primary_node:
          hosts:
            node01: {}
        controlplane_nodes:
          hosts:  
            node01: {}
            node02: {}
            node03: {}
        worker_nodes:
          hosts:
            node04: {}
            node05: {}
            node06: {}
            node07: {}
            node08: {}
            node09: {}
            node10: {}
