allnodes:
  hosts:
    node01:
      ansible_host: node01
      ansible_user: pleejr
    node02:
      ansible_host: node02
      ansible_user: pleejr
    node03:
      ansible_host: node03
      ansible_user: pleejr
    node04:
      ansible_host: node04
      ansible_user: pleejr
    node05:
      ansible_host: node05
      ansible_user: pleejr
  children:
      controlplane:
        hosts:  
          node01: {}
          node02: {}
      workers:
        hosts:
          node03: {}
          node04: {}
          node05: {}