all:
  hosts:
    node01:
      ansible_host: node01
      ansible_user: pleejr
      node_ip_allocation: 10.0.20.1
    node02:
      ansible_host: node02
      ansible_user: pleejr
      node_ip_allocation: 10.0.20.2
    node03:
      ansible_host: node03
      ansible_user: pleejr
      node_ip_allocation: 10.0.20.3
    node04:
      ansible_host: node04
      ansible_user: pleejr
      node_ip_allocation: 10.0.20.4
    node05:
      ansible_host: node05
      ansible_user: pleejr
      node_ip_allocation: 10.0.20.5
    node06:
      ansible_host: node06
      ansible_user: pleejr
      node_ip_allocation: 10.0.20.6
    node07:
      ansible_host: node07
      ansible_user: pleejr
      node_ip_allocation: 10.0.20.7
    node08:
      ansible_host: node08
      ansible_user: pleejr
      node_ip_allocation: 10.0.20.8
    node09:
      ansible_host: node09
      ansible_user: pleejr
      node_ip_allocation: 10.0.20.9
    node10:
      ansible_host: node10
      ansible_user: pleejr
      node_ip_allocation: 10.0.20.10
  children:
    all_groups:
      children:
        local:
          hosts:
            localhost:
              ansible_connection: local
        all_nodes:
          hosts:
            node01: {}
            node02: {}
            node03: {}
            node04: {}
            node05: {}
            node06: {}
            node07: {}
            node08: {}
            node09: {}
            node10: {}
        primary_node:
          hosts:
            node01: {}
        controlplane_nodes:
          hosts:  
            node01: {}
            node02: {}
            node03: {}
        worker_nodes:
          hosts:
            node04: {}
            node05: {}
            node06: {}
            node07: {}
            node08: {}
            node09: {}
            node10: {}
