- name: Get Ubuntu Codename
  ansible.builtin.command: lsb_release -sc
  register: ubuntu_codename
  changed_when: false

- name: Get Dpkg Architecture
  ansible.builtin.command: dpkg --print-architecture
  register: dpkg_arch
  changed_when: false

- name: Verify Docker Repository
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/docker.list
    content: |
      deb [arch={{ dpkg_arch.stdout }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ubuntu_codename.stdout }} stable
    owner: root
    group: root
    mode: '0644'

- name: Update Apt Package Cache
  ansible.builtin.apt:
    update_cache: yes
