---
- name: Ensure Python3-Pip Installed
  ansible.builtin.package:
    name: python3-pip
    state: present

- name: Install Kubernetes Python Module
  ansible.builtin.apt:
    name: python3-kubernetes
    state: present
    update_cache: yes