- name: Persist Kernel Modules Across Reboots
  ansible.builtin.copy:
    dest: /etc/modules-load.d/k8s.conf
    content: |
      overlay
      br_netfilter
    owner: root
    group: root
    mode: '0644'

- name: Load Kernel Module - overlay
  ansible.builtin.modprobe:
    name: overlay
    state: present

- name: Load Kernel Module - br_netfilter
  ansible.builtin.modprobe:
    name: br_netfilter
    state: present
